#!/usr/bin/env bash
  
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    cat <<EOF
Usage ncs-netsim-del  -v | --version

Displays the version number of this ncs-netsim-del release
See manpage for ncs-netsim-del for more info. 

EOF
fi

if [ "$NCSNETDIRDEL" = "" ]; then
    version='1.0.0'
    echo NCSNETDIRDEL variable is not set, recommended to set the variable.
else 
    version=<$NCSNETDIRDEL/../../.version
fi

echo ncs-netsim-del $version

# done..!
