#!/usr/bin/env bash

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    cat <<EOF
Usage ncs-netsim-del  device <DeviceNames>

Deletes the list of devices given from <NetsimDir>
See manpage for ncs-netsim-del for more info. 

EOF
fi

# done..!