#!/usr/bin/env bash
  
if [ "$1" = "--help" ]; then
    cat <<EOF
Usage ncs-netsim-del  -v | --version

Displays the version number of this ncs-netsim-del release
See manpage for ncs-netsim-del for more info. 

EOF
fi

if [ "$NCSNETSIMDEL" = "" ]; then
    version='1.0.0'
    echo NCSNETSIMDEL variable is not set, recommended to set the variable.
else 
    version=`cat $NCSNETSIMDEL/../.version`
fi

echo ncs-netsim-del $version
# done..!
